### ISSUE TITLE
Scan QRCode from screen and import from clipboard failed

### ISSUE THREAD

**Issue by dr1llc4t** [JimLee1996/TrojanX#1]
**Describe the bug**
Scan QRCode from screen and import from clipboard failed, only manually import works.

**To Reproduce**
Use scan QRCode from screen or import from clipboard

**Expected behavior**
Everything works just like ShadowsocksNG

**Screenshots**
<img width="382" alt="截屏2020-02-2720 52 39" src="https://user-images.githubusercontent.com/23226773/75446828-2136c400-59a3-11ea-8a19-6d78226334be.png">

**System and TrajanX version: 
 - OS Version: Mac OS Catalina 10.15.3
 - TrajanX: Version 1.0

**Comment by caesarjing** [comment]
https://github.com/JimLee1996/TrojanX/pull/2

**Comment by JimLee1996** [comment]
please see https://github.com/JimLee1996/TrojanX/releases/tag/0.2

**Comment by lixingmao** [comment]
貌似新版url 识别没有做编解码，如果 ULR 中包含特殊字符或者中文（一般在 URL 中`#`号后面部分），就会造成识别失败； 望后续有时间能修正。

**Comment by caesarjing** [comment]
https://github.com/JimLee1996/TrojanX/commit/3cd0b24addf142c2aff4575dc62de81b200ed789#r37646079 这里的remark没有传参传进去 @timelessg

**Comment by timelessg** [comment]
remark is not valid parameter of trojan url,and you can see more at trojan's repository @caesarjing

**Comment by caesarjing** [comment]
ok. so the client has to define the standard for remark if we were to implement this feature. thanks for clarification @timelessg
