### ISSUE TITLE
trojan.json自行修改一些参数后打开程序又还原了

### ISSUE THREAD

**Issue by Kyo628** [JimLee1996/TrojanX#21]
例: (加粗部分)
{
  "remote_addr" : "xxxxxxxxx",
  "remote_port" : 443,
  "password" : [
    "xxxxxxxxx"
  ],
  "log_level" : 2,
  "ssl" : {
    "verify" : **true**,
    "verify_hostname" : **true**,
    "cipher" : "",
    "cipher_tls13" : "**TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384**",
    "cert" : "",
    "alpn" : [
      "h2"
    ],
    "curves" : "",
    "sni" : "",
    "reuse_session" : true,
    "session_ticket" : false
  },
  "local_addr" : "127.0.0.1",
  "run_type" : "client",
  "tcp" : {
    "no_delay" : true,
    "fast_open" : false,
    "fast_open_qlen" : 20,
    "keep_alive" : true,
    "reuse_port" : false
  },
  "local_port" : 1080
}

**Comment by JimLee1996** [comment]
please see [here](https://github.com/JimLee1996/TrojanX/blob/6a5dc68467885e9e1d87361913850fdf6a8b427b/TrojanX/LaunchAgentUtils.swift#L103-L136). The client will fresh the config every time an event happens. Try `chmod 444 trojan.json` to avoid writing the new config.

**Comment by Kyo628** [comment]
> please see [here](https://github.com/JimLee1996/TrojanX/blob/6a5dc68467885e9e1d87361913850fdf6a8b427b/TrojanX/LaunchAgentUtils.swift#L103-L136). The client will fresh the config every time an event happens. Try `chmod 444 trojan.json` to avoid writing the new config.

THX~!
