### ISSUE TITLE
`编辑PAC用户自定义规则`无效

### ISSUE THREAD

**Issue by KingAmo** [JimLee1996/TrojanX#24]
### Describe the bug
PAC模式下，使用`编辑PAC用户自定义规则`功能，按照 https://adblockplus.org/en/filter-cheatsheet 的规则，加入以下一行
```
@@||google.com
```
规则忽略google.com，直连google，理应无法访问
实则可以访问，可以判断此功能失效

### Expected behavior
事实上，我是想在PAC模式下，仍使用代理访问`github.com`，然而添加如下规则似乎没生效
```
||github.com
```

**Comment by zhuang00** [comment]
要删除最上面的!!注释,再添加,最后关闭trojan再开，就会生效。

**Comment by xiangbohua** [comment]
原来要删除上面的注视啊。
我甚至把user-rule的规则全部学了一遍，发现没什么用，让我一度怀疑我的学习能力

**Comment by xiangbohua** [comment]
我测试了下，每次编辑User-Rule都是要重新打开才会生效。

**Comment by David0653116** [comment]
PAC自动模式下，只写了一条：
!!tunnelblick.net
怎么测试都是不生效，默认情况下网站一直打不开，全局模式就可以。
删除了上边的注释，重启了客户端也都不行。

**Comment by JamesK0621** [comment]
> 要删除最上面的!!注释,再添加,最后关闭trojan再开，就会生效。

成功了，多谢帮助

**Comment by crifan** [comment]
此处，加了规则：

```
||github.com
```

后，根据提示内容：

> ! 修改完成后请更新为GFWList一次方可生效。

去更新GFWList:

* `Trojan`->`PAC模式`->`更新PAC为GFWList`

即可：无需重启Trojan，即可生效
