### ISSUE TITLE
新mac os版本11.0.1不能使用

### ISSUE THREAD

**Issue by MultiLi** [JimLee1996/TrojanX#38]
开启了trojan之后直接无法连接网络

**Comment by k-zha14** [comment]
Face the same question, wait for more feedbacks

**Comment by yxrwaytt** [comment]
TrojanX-fix-macOS-BigSur.zip安装了这个依然不能用。

**Comment by MultiLi** [comment]
换成trojan 1.16.0之后就好了

**Comment by owen8372** [comment]
我也遇到同样问题，请问你是将trojanx中的trojan版本替换掉了吗？

**Comment by k-zha14** [comment]
> 我也遇到同样问题，请问你是将trojanx中的trojan版本替换掉了吗？

参考这个就行issue就行，https://github.com/JimLee1996/TrojanX/issues/31
