### ISSUE TITLE
Http proxy 在big sur下一直报connection refused

### ISSUE THREAD

**Issue by noachianark** [JimLee1996/TrojanX#46]
MacOS 11.5.2
TrojanX 1.15.1
privoxy v3.0.26

浏览器正常

terminal中：

➜  ~ export http_proxy=http://127.0.0.1:1081;export https_proxy=http://127.0.0.1:1081;
➜  ~ curl www.google.co.jp
curl: (7) Failed to connect to 127.0.0.1 port 1081: Connection refused

**Comment by rurico** [comment]
解决方法：下载最新的trojan的binary，然后手动执行`https://github.com/JimLee1996/TrojanX/blob/master/TrojanX/install_trojan.sh`这个脚本中的命令，手动替换掉trojan即可。

**Comment by noachianark** [comment]
解决了，谢谢
